runtime: python312
instance_class: F4_1G

automatic_scaling:
  min_instances: 1
  
inbound_services:
  - warmup

handlers:
  # Serve API routes
  - url: /(chat|tts)(.*)
    script: auto

  # Serve all static files from Angular build
  - url: /(.*\.(js|css|html|jpg|png|gif|svg|ico|map|woff|woff2|eot|ttf))
    static_files: dist/browser/\1
    upload: dist/browser/(.*\.(js|css|html|jpg|png|gif|svg|ico|map|woff|woff2|eot|ttf))

  # Serve 'index.html' for all other routes
  - url: /*
    static_files: dist/browser/index.html
    upload: dist/browser/index.html
