runtime: python312
instance_class: F4_1G

handlers:
  # Serve API routes
  - url: /(chat|tts)(.*)
    script: auto

  # Serve all static files from Angular build
  - url: /
    static_dir: dist/browser

  # Serve 'index.html' for all other routes
  - url: /.*
    static_files: dist/browser/index.html
    upload: dist/browser/index.html
